version: '3'

services:
  backend:
    container_name: backend
    image: demiz/backend-release:1.0.3
    env_file: .env
    volumes:
      - ./backend/src:/app/src
      - /app/node_modules
    ports:
      - '4000:4000'
    restart: always
    networks:
      - backend

  frontend:
    container_name: frontend
    image: demiz/frontend-release:1.0.3
    env_file: .env
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '8080:8080'
    restart: always
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: nest_project
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
    networks:
      - backend

volumes:
  postgres_data:
networks:
  backend:
  frontend:
