version: '3'

services:
  backend:
    container_name: backend
    image: demiz/backend-release:1.0.3
    env_file: .env
    ports:
      - '4000:3000'
    restart: always
    networks:
      - backend

  frontend:
    container_name: frontend
    image: demiz/frontend-release:1.0.3
    env_file: .env
    ports:
      - '3001:3000'
    restart: always
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    env_file: .env
    restart: always
    volumes:
      - postgres_data:/data/postgres
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - backend
      
volumes:
  postgres_data:
networks:
  backend:
  frontend: 